src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Length;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * 
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotNull
     * @Length(
     * min=2,
     * max=100,
     * minMessage = "Your author name must be at least {{ limit }} characters long",
     * maxMessage = "Your author name cannot be longer than {{ limit }} characters")
     *
     */
    private $auteur;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     *@Length(
     * min=2,
     * max=255,
     * minMessage = "Your article body must be at least {{ limit }} characters long",
     * maxMessage = "Your article body cannot be longer than {{ limit }} characters")
     * 
     */
    private $corps;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank
     */
    private $creation_date;

    /**
     * @ORM\Column(type="string", length=45)
     * @ASSERT\NotBlank
     * @Length(
     * min=2,
     * max=45,
     * minMessage = "Your title must be at least {{ limit }} characters long",
     * maxMessage = "Your title cannot be longer than {{ limit }} characters")
     */
    private $titre;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="article", orphanRemoval=true)
     */
    private $comments;

    /**
     * @Assert\NotBlank
     * @ORM\Column(type="string", length=10)
     * @Length(
     * min=0,
     * max=10,
     * minMessage = "Your category name must be at least {{ limit }} characters long",
     * maxMessage = "Your category name cannot be longer than {{ limit }} characters")
     */
    private $categorie;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuteur(): ?string
    {
        return $this->auteur;
    }

    public function setAuteur(string $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }

    public function getCorps(): ?string
    {
        return $this->corps;
    }

    public function setCorps(string $corps): self
    {
        $this->corps = $corps;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use App\Entity\Article;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder

            ->add('creation_date', DateType::class)
            ->add('auteur', TextType::class,[
                  'label' => 'auteur'
              ])
              ->add('titre', TextType::class,[
                  'label' => 'titre'
              ])
              ->add('corps', TextareaType::class,[
                  'label' => 'corps',
              ],
              array('attr' => array('class' => 'ckeditor') )
              )
              ->add('categorie', ChoiceType::class,[
                  'choices' => [
                      'health' => 'health',
                      'security' => 'security',
                      'common things' => 'common',
                      'thoughts' => 'thoughts'
                  ]
              ])
              
              
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

use App\Entity\Article;
use App\Entity\Comment;
use App\Entity\User;
use App\Entity\Owner;
use App\Entity\Adopter;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Response;
use App\Form\ArticleType;
use App\Form\CommentType;
use App\Form\OwnerType;
use App\Form\AdopterType;

use Symfony\Component\Form\Forms;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Form\Extension\Csrf\CsrfExtension;
use Symfony\Component\Security\Csrf\TokenStorage\SessionTokenStorage;
use Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator;
use Symfony\Component\Security\Csrf\CsrfTokenManager;

//include paginator interface
use Knp\Component\Pager\PaginatorInterface;
use knp_paginator;

/** @Route("/blog", name="blog/") */
class BlogController extends AbstractController
{

    /**
     * @Route("/cats", name="cats")
     */
    public function CatsBreed()
    {
        return $this->render('blog/CatsBreed.html.twig');
    }

    /**
     * @Route("/dogs", name="dogs")
     */
    public function testDogsBreed()
    {
        return $this->render('blog/DogsBreed.html.twig');
    }

    /**
     * @Route("/accueil", name="accueil")
     */
    public function accueil(Request $request, PaginatorInterface $paginator)
    {

        $query = $this->getDoctrine()
            ->getRepository(Article::class)
            ->createQueryBuilder('articles')
            
            // ->from('Article', 'articles')
            ->addOrderBy('articles.id', 'ASC')
            ->getQuery();

        $pagination = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            5
        );
        $articles = $this->getDoctrine()
        ->getRepository(Article::class)
        ->findAll();

        if (!$articles) {
            throw $this->createNotFoundException(
                'No articles found'
            );
        }

        return $this->render('blog/accueil.html.twig', [
            'articles' => $articles,
            'pagination' => $pagination,
            
        ]);
    }

    /**
     * @Route("/profile/{id}", name="profile", requirements={"^[1-9]\d*$"})
     */
    public function showProfile($id, Request $request, User $user)
    {
        $user = $this->getDoctrine()
            ->getRepository(User::class)
            ->find($id);

        // dd($user);
        if (!$user) {
            throw $this->createNotFoundException(
                'No user found for id ' . $id
            );
        }

        return $this->render('blog/user/profile.html.twig', [
            'user' => $user,
  ]);
    }

    /**
     * @Route("/profile/{id}/Owner/add", name="owner/add", requirements={"^[1-9]\d*$"})
     */
    public function addOwner($id,Request $request, User $user)
    {
        $user = $this->getDoctrine()
            ->getRepository(User::class)
            ->find($id);

        if (!$user) {
            throw $this->createNotFoundException(
                'No user found for id ' . $id
            );
        }

          // creates an owner
          $owner = new Owner();

        
          $form = $this->createForm(OwnerType::class, $owner);
  
                $form->handleRequest($request);
  
                if ($form->isSubmitted() && $form->isValid()) {
                    // $form->getData() holds the submitted values
                    // but, the original `$owner` variable has also been updated
                    $owner = $form->getData();
            
                    $entityManager = $this->getDoctrine()->getManager();
                    // $owner->setUser($id);
                    $entityManager->persist($owner);
                    $entityManager->flush();
                    
                    $this->addFlash(
                      'notice',
                      'Votre owner à été créer !'
                  );
                }

                return $this->render('blog/profile/newOwner.html.twig', [
                    'user' => $user,
                    'form' => $form->createView(),
          ]);

    }

    /**
     * @Route("/profile/{id}/Adopter/add", name="adopter/add", requirements={"^[1-9]\d*$"})
     */
    public function addAdopter($id,Request $request, User $user)
    {
        $user = $this->getDoctrine()
            ->getRepository(User::class)
            ->find($id);

        if (!$user) {
            throw $this->createNotFoundException(
                'No user found for id ' . $id
            );
        }

          // creates an adopter
          $adopter = new Adopter();

          $form = $this->createForm(AdopterType::class, $adopter);
  
                $form->handleRequest($request);
  
                if ($form->isSubmitted() && $form->isValid()) {
                    // $form->getData() holds the submitted values
                    // but, the original `$owner` variable has also been updated
                    $adopter = $form->getData();
                    // $adopter->setUser($id);
                    $entityManager = $this->getDoctrine()->getManager();
                    $entityManager->persist($adopter);
                    $entityManager->flush();
                    
                    $this->addFlash(
                      'notice',
                      'Vous avez le statut de demandeur !'
                  );
                }

                return $this->render('blog/profile/newAdopter.html.twig', [
                    'user' => $user,
                    'form' => $form->createView(),
          ]);
    }
    
    /**
     * @Route("/show/{id}", name="show", requirements={"^[1-9]\d*$"})
     */
    public function show($id, Request $request, Article $article)
    {
        $article = $this->getDoctrine()
            ->getRepository(Article::class)
            ->find($id);

        if (!$article) {
            throw $this->createNotFoundException(
                'No article found for id ' . $id
            );
        }

        $comments = $article->getComments();

        // creates a comment
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {

                $entityManager = $this->getDoctrine()->getManager();
                $article->addComment($comment);
                $entityManager->persist($comment);
            //   $comment->setArticle($article);
                $entityManager->flush();
                
                $this->addFlash(
                'notice',
                'Votre commentaire à été créer !'
            );
            }

        $articles = $this->getDoctrine()
        ->getRepository(Article::class)
        ->findAll();

        if (!$articles) {
            throw $this->createNotFoundException(
                'No articles found'
            );
        }
        return $this->render('blog/articles/article.html.twig', [
            'article' => $article,
            'articles' => $articles,
            'form' => $form->createView(),
  ]);
    }

    // Article section

    /**
     * @Route("/show", name="show_all")
     */
    public function showAll(Request $request, PaginatorInterface $paginator)
    {

        $articles = $this->getDoctrine()
            ->getRepository(Article::class)
            ->findAll();

        $query = $this->getDoctrine()
            ->getRepository(Article::class)
            ->createQueryBuilder('articles')
            
            // ->from('Article', 'articles')
            ->addOrderBy('articles.id', 'ASC')
            ->getQuery();

        $pagination = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            5
        );
        
        if (!$articles) {
            throw $this->createNotFoundException(
                'No articles found'
            );
            $this->addFlash(
                'danger',
                'No articles found!'
            );
        }
        return $this->render('blog/articles/articles.html.twig', [
            'articles' => $articles,
            'pagination' => $pagination,
            ]);
    }

    /**
     * @Route("/article/new", name="article/new")
     */
    public function addArticle(Request $request)
    {
        // creates a Session object from the HttpFoundation component
        $session = new Session();

        $csrfGenerator = new UriSafeTokenGenerator();
        $csrfStorage = new SessionTokenStorage($session);
        $csrfManager = new CsrfTokenManager($csrfGenerator, $csrfStorage);

        $formFactory = Forms::createFormFactoryBuilder()
        
            ->addExtension(new CsrfExtension($csrfManager))
            ->getFormFactory();


        // creates an article
        $article = new Article();

        
        $form = $this->createForm(ArticleType::class, $article);

              $form->handleRequest($request);

              if ($form->isSubmitted() && $form->isValid()) {
                  // $form->getData() holds the submitted values
                  // but, the original `$article` variable has also been updated
                  $article = $form->getData();
          
                  $entityManager = $this->getDoctrine()->getManager();
                  $entityManager->persist($article);
                  $entityManager->flush();
                  
                  $this->addFlash(
                    'notice',
                    'Votre article à été créer !'
                );
              }

templates/blog/articles/article.html.twig
{% extends 'section/layout.html.twig' %}

{% block body %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light articles-menu">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% for article in articles %}
                    <li class="nav-item active">
                        <a class="nav-link" href={{ path('blog/show',{ "id" : article.id} ) }}>
                            {{ article.id|e }}
                        </a>
                    </li>
                {% endfor %}
                <a class="btn btn-primary" href={{ path('blog/destroy',{ 'id' : article.id} ) }}>
                    <button>effacer
                        {{ article.id|e }}</button>
                </a>
            </ul>
        </div>
    </nav>
    <div>
        <span>{{ article.auteur }}</span>
        <span>{{ article.titre }}</span>
        <span>{{ article.corps }}</span>
        <span>{{ article.creationDate|date("m/d/Y", "Europe/Paris") }}</span>
    </div>

    <div class="container">
        <div class="table-responsive">
            <table class="table table-striped table-dark">
                
                {% for comment in article.comments %}
                  {% if comment is defined and comment is not null %}
                    <p>{{ comment.id }} exists</p>
                  {% else %}
                    <p>The comment does not exists</p>
                  {% endif %}
                {% endfor %}
                </h1>
                <tbody>
                    <tr>
                        <th scope="row">id</th>
                        {% for comment in article.comments %}
                          {% if comment.id|length <= 0 %}
                            <th scope="col">Pas d'id</th>
                          {% else %}
                          <th scope="col">{{  comment.id  }}</th>
                          {% endif %}
                        {% endfor %}
                    </tr>
                    <tr>
                        <th scope="row">auteur</th>
                        {% for comment in article.comments %}
                            {% if comment.author|length <= 0 %}
                              <th scope="col">Pas d'auteur</th>
                            {% else %}
                              <th scope="col">{{  comment.author  }}</th>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    <tr>
                        <th scope="row">description</th>
                        {% for comment in article.comments %}
                            {% if comment.description|length <= 0 %}
                              <th scope="col">Pas de description</th>
                            {% else %}
                              <th scope="col">{{  comment.description  }}</th>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    <tr>
                        <th scope="row">corps</th>
                        {% for comment in article.comments %}
                             {% if comment.corps|length <= 0 %}
                              <th scope="col">Pas de corps</th>
                            {% else %}
                              <th scope="col">{{  comment.corps  }}</th>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    <tr>
                        <th scope="row">destroy</th>
                        {% for comment in article.comments %}
                            <td>
                                <a class="btn btn-primary" href={{ path('blog/destroyComment',{ 'id' : comment.id} ) }}>
                                    <button>effacer
                                        {{ comment.id }}</button>
                                </a>
                            </td>
                        {% endfor %}
                    </tr>
                </tbody>
            </table>
            
        </div>
    </div>

    <div class="container">
        <section>
            {{form_start(form)}}
            {# general errors #}
            {{form_errors(form)}}

            {{ form_label(form.author) }}
            {{ form_widget(form.author) }}
            {# fields errors #}
            {{ form_errors(form.author) }}

            {{ form_label(form.description) }}
            {{ form_widget(form.description) }}
            {# fields errors #}
            {{ form_errors(form.description) }}

            {{ form_label(form.corps) }}
            {{ form_widget(form.corps) }}
            {# fields errors #}
            {{ form_errors(form.corps) }}

            <a class="btn btn-primary">
                <button>submit</button>
            </a>

            {{form_end(form)}}

        </div>
    {% endblock %}

templates/blog/articles/articles.html.twig
{% extends 'section/layout.html.twig' %}

{% block body %}
    <div class="table-responsive">
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="row">#</th>
                {% for article in pagination %}
        
                    <th>
                        <a class="btn btn-primary" href={{ path('blog/show',{ "id" : article.id}) }}><button>{{  article.id  }}</button></a>
                    </th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">auteur</th>
                {% for article in pagination %}
                    <th>{{  article.auteur  }}</th>
                {% endfor %}
            </tr>
             <tr>
                <th scope="row">titre</th>
                {% for article in pagination %}
                    {% if article.titre|length <= 0 %}
                        <th>Pas de titre</th>
                    {% else %}
                        <th>{{  article.titre  }}</th>
                    {% endif %}
                {% endfor %}
            </tr>
            <tr>
                <th scope="row">Excerpt article</th>
                {% for article in pagination %}
                    {% if article.corps|length > 30 %}
                        <th>{{  article.corps[:31]  }}</th>
                    {% else %}
                        <th>{{  article.corps  }}</th>
                    {% endif %}
                {% endfor %}
            </tr>
            <tr>
                <th scope="row">suppression</th>
                {% for article in pagination %}
                    <th>
                        <a class="btn btn-primary" href={{ path('blog/destroy',{ "id" : article.id}) }}><button>destroy</button></a>
                    </th>
                {% endfor %}
            </tr>
             <tr>
                <th scope="row">Modification</th>
                {% for article in pagination %}
                    <th>
                        <a class="btn btn-info" href={{ path('blog/article/edit', {"id" : article.id}) }} tabindex="-1" aria-disabled="true">Update</a>
                    </th>
                {% endfor %}
            </tr>
        </tbody>
    </table>

  
<div class="navigation">
    {{ knp_pagination_render(pagination) }}
</div>
    

{% endblock %}

templates/blog/articles/edit.html.twig
{% extends 'section/layout.html.twig' %}


{% block title %}Update an article !{% endblock %}

{% block body %}
{{ article.auteur }}
{{ article.titre }}
{{ article.corps }}
{{ article.creationDate|date("m/d/Y", "Europe/Paris") }}
<section>
{{form_start(form)}}
{# general errors #}
{{form_errors(form)}}

{{ form_label(form.auteur) }}
{{ form_widget(form.auteur) }}
{# fields errors #}
{{ form_errors(form.auteur) }}

{{ form_label(form.titre) }}
{{ form_widget(form.titre) }}
{# fields errors #}
{{ form_errors(form.titre) }}

{{ form_label(form.corps) }}
{{ form_widget(form.corps) }}
{# fields errors #}
{{ form_errors(form.corps) }}

{{ form_label(form.creation_date) }}
{{ form_widget(form.creation_date) }}
{# fields errors #}
{{ form_errors(form.creation_date) }}

<a class="btn btn-primary" href={{ path('blog/article/edit',{ 'id' : article.id}) }}><button>edit</button></a>

{{form_end(form)}}

</section>
{% endblock %}

templates/blog/articles/new.html.twig
{% extends 'section/layout.html.twig' %}


{% block title %}Add an article !{% endblock %}

{% block body %}
{{ article.auteur }}
{{ article.corps }}
{{ article.creationDate|date("m/d/Y", "Europe/Paris") }}
<section>
{{form_start(form)}}
{# general errors #}
{{form_errors(form)}}

{{ form_label(form.auteur) }}
{{ form_widget(form.auteur) }}
{# fields errors #}
{{ form_errors(form.auteur) }}

{{ form_label(form.titre) }}
{{ form_widget(form.titre) }}
{# fields errors #}
{{ form_errors(form.titre) }}

{{ form_label(form.corps) }}
{{ form_widget(form.corps) }}
{# fields errors #}
{{ form_errors(form.corps) }}

{{ form_label(form.creation_date) }}
{{ form_widget(form.creation_date) }}
{# fields errors #}
{{ form_errors(form.creation_date) }}

<a class="btn btn-primary" href={{ path('blog/article/new') }}><button>créer</button></a>

{{form_end(form)}}

</section>
{% endblock %}